
server:
  port: 8081 #项目端口

mybatis-plus:
  mapper-locations: classpath*:com/stylefeng/guns/rest/**/mapping/*.xml
  typeAliasesPackage: com.stylefeng.guns.rest.common.persistence.model

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.108.93.119:3306/school_bus?serverTimeZone=UTC&useSSL=false&characterEncoding=UTF-8
      username: root
      password: mai
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        initial-size: 5
        max-active: 20
        min-idle: 5
        max-wait: 3000
        timeBetweenEvictionRunsMillis: 60000
        pool-prepared-statements: false
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        web-stat-filter:
          enabled: true
          url-pattern: "/*"
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        stat-view-servlet:
          login-username: admin
          login-password: 123
  redis:
    database: 0
    host: 39.108.93.119
    port: 6179
    password: 123
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8


logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: sb-user.log

dubbo:
  application:
    name: guns-user
  registry:
    protocol: zookeeper
    address: 39.108.93.119:2181
  protocol:
    port: 20880

apache:
  rocketmq:
    consumer:
      pushConsumer: school-bus
    namesrvAddr: 39.108.93.119:9876